### ISSUE TITLE
How to use it to deploy Django 2, Wagtail 2 sites?

### ISSUE THREAD

**Issue by ScarletMcLearn** [texperience/wagtail-pythonanywhere-quickstart#2] opened 2018-10-26 07:32 UTC
How to use it to deploy Django 2, Wagtail 2 sites?

Any updates?

Does this still work?

**Comment by timorieber** [comment] 2018-10-27 10:05
Closed as duplicate of #1. Please read https://github.com/texperience/wagtail-pythonanywhere-quickstart/issues/1#issuecomment-433607597 for more details.

**Closed as completed by timorieber** 2018-10-27 10:05 UTC
